# File: scenarios/ANN/docker-compose-ols.yml
services:
  learning_base:
    image: il1aa/learning-base-student-performance-predictor:v1.0
    volumes:
      - ai_system:/tmp
    command:
      - /bin/sh
      - "-c"
      - |
        rm -rf /tmp/learningBase/ && cp -r /learningBase/ /tmp/;

  knowledge_base:
    image: il1aa/knowledge-base-student-performance-predictor:v1.0
    volumes:
      - ai_system:/tmp
    command:
      - /bin/sh
      - "-c"
      - |
        rm -rf /tmp/knowledgeBase/ && cp -r /knowledgeBase/ /tmp/;

  activation_base:
    image: il1aa/activation-base-student-performance-predictor:v1.0
    volumes:
      - ai_system:/tmp
    command:
      - /bin/sh
      - "-c"
      - |
        rm -rf /tmp/activationBase/ && cp -r /activationBase/ /tmp/;

  code_base:
    image: il1aa/code-base-student-performance-predictor:v1.0-amd64
    volumes:
      - ai_system:/tmp
    depends_on:
      - knowledge_base
      - activation_base
    command:
      - /bin/sh
      - "-c"
      - |
        rm -rf /tmp/codeBase/ && cp -r /codeBase/ /tmp/;
        python /tmp/codeBase/OLS_activation.py;
        tail -f /dev/null
volumes:
  ai_system:
    external: true