version: "3.9"
services:
  activationBase:
    build: .
    image: il1aa/knowledge-base-student-performance-predictor:v1.0
    container_name: knowledgeBase_container
    volumes:
      - ai_system:/tmp
    command:
      - /bin/sh
      - "-c"
      - |
        rm -rf /tmp/knowledgeBase/ && cp -r /knowledgeBase/ /tmp/;

volumes:
  ai_system:
    external: true
