version: "3.9"
services:
  learningBase:
    build: .
    image: learningbase_student-performance-predictor:latest
    container_name: learningBase_container
    volumes:
      - ai_system:/tmp
    command:
      - /bin/sh
      - "-c"
      - |
        rm -rf /tmp/learningBase/ && cp -r /learningBase/ /tmp/;

volumes:
  ai_system:
    external: true
