version: "3.9"
services:
  learningBase:
    build:
      context: ../../../
      dockerfile: docker/images/learningBase/Dockerfile
    image: learningbase_student-performance-predictor:latest
    container_name: learningBase_container
    volumes:
      - ai_system:/tmp # Shared volume
      - learningBase_data:/tmp/learningBase # LearningBase-specific data
volumes:
  ai_system: # Shared volume for data persistence
    external: true
  learningBase_data: # Volume specific to learningBase
  activationBase_data: # Volume specific to activationBase
