version: "3.9"
services:
  learningBase:
    build: .
    image: il1aa/learning-base-student-performance-predictor:v1.0
    container_name: learningBase_container
    volumes:
      - ai_system:/tmp
    command:
      - /bin/sh
      - "-c"
      - |
        rm -rf /tmp/learningBase/ && cp -r /learningBase/ /tmp/;

volumes:
  ai_system:
    external: true
