version: "3.9"
services:
  activationBase:
    build: .
    image: activationbase_student-performance-predictor:latest
    container_name: activationBase_container
    volumes:
      - ai_system:/tmp
    command:
      - /bin/sh
      - "-c"
      - |
        rm -rf /tmp/activationBase/ && cp -r /activationBase/ /tmp/;

volumes:
  ai_system:
    external: true
