version: "3.9"
services:
  activationBase:
    image: activationbase_student-performance-predictor:latest
    container_name: activationBase_container
    volumes:
      - ai_system:/tmp

volumes:
  ai_system:
    external: true
