version: "3.9"
services:
  activationBase:
    build:
      context: ../../../
      dockerfile: docker/images/activationBase/Dockerfile
    image: activationbase_student-performance-predictor:latest
    container_name: activationBase_container
    volumes:
      - ai_system:/tmp # Shared volume
      - activationBase_data:/tmp/activationBase # ActivationBase-specific data

volumes:
  ai_system: # Shared volume for data persistence
    external: true
  learningBase_data: # Volume specific to learningBase
  activationBase_data: # Volume specific to activationBase
