version: "3.9"
services:
  activationBase:
    build: .
    image: il1aa/code-base-student-performance-predictor:v1.0-amd64
    container_name: codeBase_container
    volumes:
      - ai_system:/tmp
    command:
      - sh
      - "-c"
      - |
        rm -rf /tmp/codeBase/ && cp -r /codeBase/ /tmp/;

volumes:
  ai_system:
    external: true
