version: "3.9"
services:
  activationBase:
    build:
      context: ../../../
      dockerfile: docker/images/codeBase/Dockerfile
    image: codebase_student-performance-predictor:latest
    container_name: codeBase_container
    volumes:
      - ai_system:/tmp # Shared volume

volumes:
  ai_system:
    external: true
